[tools]
checkov = "latest"
conftest = "latest"
go = "latest"
golangci-lint = "latest"
helm = "latest"
java = "temurin-25"
jq = "latest"
kubectl = "latest"
kustomize = "latest"
maven = "latest"
node = "latest"
opa = "latest"
opentofu = "latest"
pipx = "latest"
python = "latest"
regal = "latest"
skaffold = "latest"
spectral = "latest"
terraform = "latest"
tflint = "latest"
yamllint = "latest"
yq = "latest"

[settings]
idiomatic_version_file_enable_tools = ["terraform", "node", "python", "java", "go", "opentofu"]
